export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  studentNew: "/students/new",
  classes: "/classes",
  notices: "/notices",
  auditLogs: "/audit-logs",
  students: "/students",
  studentDetail: (id: string) => `/students/${id}`,
  studentEdit: (id: string) => `/students/${id}/edit`,
  teachers: "/teachers",
  teacherNew: "/teachers/new",
  teacherDetail: (id: string) => `/teachers/${id}`,
  teacherEdit: (id: string) => `/teachers/${id}/edit`,
  admins: "/admins",
  adminNew: "/admins/new",
  adminDetail: (id: string) => `/admins/${id}`,
  adminEdit: (id: string) => `/admins/${id}/edit`,
  settings: "/settings",
  support: "/support",
} as const;
