export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  students: "/students",
  studentNew: "/students/new",
  teachers: "/teachers",
  admins: "/admins",
  classes: "/classes",
  notices: "/notices",
  auditLogs: "/audit-logs",
  studentDetail: (id: string) => `/students/${id}`,
  studentEdit: (id: string) => `/students/${id}/edit`,
  settings: "/settings",
  support: "/support",
} as const;